apiVersion: v1
kind: Secret
metadata:
  name: estatekit-documents-api-secrets
  namespace: estatekit-documents
  labels:
    app: estatekit-documents-api
    component: secrets
    environment: production
  annotations:
    kubernetes.io/created-by: estatekit-documents-api
    secret.kubernetes.io/last-rotated: "2024-01-01T00:00:00Z"
    secret.kubernetes.io/rotation-period: "30d"
    encryption.kubernetes.io/provider: kubernetes.io/kms
    encryption.kubernetes.io/key-rotation: "true"
    encryption.kubernetes.io/rotation-period: "30d"
    audit.kubernetes.io/enabled: "true"
    audit.kubernetes.io/log-level: "RequestResponse"
    audit.kubernetes.io/retention: "90d"
    backup.kubernetes.io/enabled: "true"
    backup.kubernetes.io/schedule: "daily"
    backup.kubernetes.io/retention: "30d"
    monitoring.kubernetes.io/enabled: "true"
    monitoring.kubernetes.io/alert-secret-access: "true"
    monitoring.kubernetes.io/alert-rotation-due: "true"
    monitoring.kubernetes.io/alert-validation-failure: "true"
    validation.kubernetes.io/required-secrets: "true"
    validation.kubernetes.io/no-plaintext: "true"
    validation.kubernetes.io/namespace-match: "true"
    validation.kubernetes.io/key-format: "true"
    validation.kubernetes.io/rbac-compliance: "true"
type: Opaque
stringData:
  AWS_REGION: ${AWS_REGION}  # Pattern: ^[a-z]{2}-[a-z]+-\d{1}$
  AWS_S3_BUCKET: ${AWS_S3_BUCKET}  # Pattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$
  AWS_TEXTRACT_QUEUE_URL: ${AWS_TEXTRACT_QUEUE_URL}  # Pattern: ^https://sqs\.[a-z0-9-]+\.amazonaws\.com/
  AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}  # Pattern: ^[a-z]{2}-[a-z]+-\d{1}_[A-Za-z0-9]+$
  AWS_COGNITO_APP_CLIENT_ID: ${AWS_COGNITO_APP_CLIENT_ID}  # Pattern: ^[a-zA-Z0-9]+$
  AWS_KMS_KEY_ID: ${AWS_KMS_KEY_ID}  # Pattern: ^[a-f0-9-]{36}$
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}  # Pattern: ^[A-Z0-9]{20}$
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}  # Pattern: ^[A-Za-z0-9/+=]{40}$
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: estatekit-documents-api-secrets-policy
  namespace: estatekit-documents
spec:
  podSelector:
    matchLabels:
      app: estatekit-documents-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: estatekit-documents-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: estatekit-documents-api-secrets-role
  namespace: estatekit-documents
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["estatekit-documents-api-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: estatekit-documents-api-secrets-rolebinding
  namespace: estatekit-documents
subjects:
  - kind: ServiceAccount
    name: estatekit-documents-api
    namespace: estatekit-documents
roleRef:
  kind: Role
  name: estatekit-documents-api-secrets-role
  apiGroup: rbac.authorization.k8s.io